### ISSUE TITLE
Permanent SAS effect on vehicles with no SAS

### ISSUE THREAD

**Issue by Kafouille** [AlexanderDzhoganov/ksp-advanced-flybywire#24]
There seems to be an SAS effect permanently active when using this, but only on vehicles that cannot have SAS (Like crafts without a Pilot kerbal or Stayputniks). This happens using KSP 0.90, FBW 1.45, with only this mod + toolbar active, on Windows 7 x64. Happens even with no inputs activated for FWB.

**Comment by JandCandO** [comment]
I had this same problem on several flights, but after restarting KSP I was not able to recreate it.
