### ISSUE TITLE
Non functional on OS X

### ISSUE THREAD

**Issue by expipiplus1** [AlexanderDzhoganov/ksp-advanced-flybywire#25]
This is probably in part due to OS X using '.dylib' as a file extension instead of '.so' or '.dll'.

Hopefully this is as simple as using "libSDL2.dylib" when compiling for OSX.

**Comment by expipiplus1** [comment]
Was this closed due to being fixed?

**Comment by AlexanderDzhoganov** [comment]
Sorry, I shoudl've elaborated. I don't have any way to test on OSX (don't own a Mac) so an "official" port is probably not going to happen, however I would gladly endorse a working port so feel free to make one and upload it to KerbalStuff and CKAN :)
