### ISSUE TITLE
SAS seems to correct the joysticks movements

### ISSUE THREAD

**Issue by Da-Boom** [AlexanderDzhoganov/ksp-advanced-flybywire#28]
Hi, upon installing this mod from the kerbal curseforge, while flying a plane, i found that when i tried to pitch my space planes nose up, the SAS would immediately try to compensate for my Xbox 360 controllers joystick movements therefore pitching up with SAS on would slowly cause the plane to stop pitching up and try to go the other way. This differs from the proper keyboard controls overriding the SAS completely, so SAS dosent fight your corrections, it only tries to correct the yaw and the roll why you are controlling the pitch. Also upon releasing the joystick, the SAS still tries to correct you for a moment, and therefore results it the whole vehicle pitching down. These problems also appear to happen when attempting to adjust yaw and roll. If this is not a bug, then i find it to be a really annoying feature. 

ksp 0.90.0.705 (with a few other mods like NEAR, B9 and KAS)
AFBW 1.4.5(x86)

**Comment by ddaf** [comment]
Hello, could you please try version 1.4.6 and confirm if this bug is still present in that version? We're still chasing down SAS-related issues after the 0.90 update.

**Comment by Da-Boom** [comment]
The bug still appears to be here, if i you pitch up with the controller and watch the pitch meter you will see when the SAS kicks in. however when you use the default keyboard controls (no controller enabled) using the W key works fine
