### ISSUE TITLE
[linux] Hat left is ignored completely

### ISSUE THREAD

**Issue by Loader009** [AlexanderDzhoganov/ksp-advanced-flybywire#32]
JoyStick: Microsoft SideWinder Force Feedback 2

Hat buttons which are detected:
- center (no button, see #31 )
- up
- up+right
- right
- down+right
- down

Hat buttons which are not detected:
- up+left
- left
- left+down

No hardware-issue.
My second JoyStick (the same type) has this issue also.

**Comment by AlexanderDzhoganov** [comment]
Thanks for the report, could you test with AFBW 1.5 and report back?

**Comment by AlexanderDzhoganov** [comment]
This has been up a while so I'm closing it. Please reopen if the issue is still present.
