### ISSUE TITLE
[W7 x64] Trim completely broken using axis/buttons

### ISSUE THREAD

**Issue by Gaiiden** [AlexanderDzhoganov/ksp-advanced-flybywire#36]
at first I couldn't even get trim commands to hold, but after I read about issue #28 I was able to toggle SAS on and off my aircraft to make it so that when I used the Alt+WASDQE keys to set trims, the control surfaces would stay deflected properly.

However if I set an axis on my joystick to a trim axis, it treats the axis like a throttle. In other words if I were to actually set it to my throttle axis, at 0 the trim would not move but if I upped my throttle a little bit the trim would start to travel - then stop if I throttled back. It only went in one direction I had to reverse the axis to travel the other way.

The button setting is broken as well - if I set the button to Pitch+ Trim activating it will pitch my trim up to max. If I use Pitch- Trim it will return to neutral, and then another tap will fully deflect it downwards.

**Comment by AlexanderDzhoganov** [comment]
Thanks for the detailed report. Could you test with the 1.5 release and report back?

**Comment by JapaMala** [comment]
I tried with the 1.5 release, using buttons for trim+ and trim-, and the trim went from 0 to max, with nowhere in between, making it slightly useless.

**Comment by AlexanderDzhoganov** [comment]
Could you try adjusting the "Discrete action step" variable in the controller config?

**Comment by m1sz** [comment]
I've tested adjusting the "Discrete action step" variable and it works. Tried it at first with 0.1 and 0.01. The ingame stock value must be between those two.

**Comment by AlexanderDzhoganov** [comment]
If anyone arrives at a decent default value please post it here and I will change it for next release.

**Comment by m1sz** [comment]
I'm using 0.01, and the steps are about what I'd like them to be, small, but noticeable

**Comment by AlexanderDzhoganov** [comment]
I'm not sure what's up with trim since 1.x so I'll have to look into it. Feel free to create a new issue with any trim- related discoveries.
