### ISSUE TITLE
Different trim effects via state.*Trim and m_Trim

### ISSUE THREAD

**Issue by conklech** [AlexanderDzhoganov/ksp-advanced-flybywire#39]
Our trim setting manifests in two different ways. First, it is copied to the relevant `FlightCtrlState.*Trim` property ([in `FlightManager.UpdateFlightProperties`](https://github.com/AlexanderDzhoganov/ksp-advanced-flybywire/blob/9e33c5f5870a8213f2874396daa30e114e2c6d9e/FlightManager.cs#L116)), which sets the resting angle when there is no controller input. Second, it is added to the input value ([in `FlightProperty.Update()`](https://github.com/AlexanderDzhoganov/ksp-advanced-flybywire/blob/796c181b3d3a3467c79ed38f174060f130839eae/FlightProperty.cs#L106)) when there *is* controller input. These two modes should be mutually exclusive.

For some reason, the two modes don't have equivalent effects: the trim adjustment has a slightly greater effect via `FlightCtrlState` (no input) than it does in `FlightProperty.Update()` (with input). For example, if I set a pitch-up trim of 0.5 with my hand off the stick, and then make a small roll or yaw movement, the pitch control immediately jumps down to something like 0.4 or 0.45, and returns to 0.5 when the controller input returns to zero. This has an unfortunate negative effect on stability...

I've tested this effect on an otherwise-unmodded Windows x86 install. Any ideas why this happens and what we might be able to do about it?

**Comment by conklech** [comment]
Perhaps the trim is applied *before* the quadratic input curve rather than *after* it? I'm not at my computer to test whether the same effect happens in linear input mode.

**Comment by AlexanderDzhoganov** [comment]
Thanks for the research. Feel free to make a PR with changes once you have clarity on how to fix this. I'm busy with other stuff at the moment but I'll be happy to merge a PR and make a release if this is fixed.

**Comment by conklech** [comment]
I think my initial analysis was wrong. Changing input curves doesn't affect the symptom.

I wonder if the trim is being double-applied when there's no input, by KSP adding, e.g. `FlightCtrlState.pitchTrim`  to the `FlightCtrlState.pitch` passed to `OnFlyByWire()`, which is then combined with our internal trim value. The SAS override mechanism discards the provided `FlightCtrlState` when there's input, eliminating the double-counting and changing the effect.

There's another strange behavior that causes me to suspect this: when a AFBW trim is in effect, keyboard and SAS input is disregarded whether or not SAS is enabled. Native trim settings (via alt-w/s) don't have this effect, and aren't disturbed by keyboard yaw/roll, but *are* completely discarded when AFBW input is in effect.

If this is correct, I'm not sure how to resolve this bug independently of #40. With SAS override disabled, I'd just rip out our internal trim in `FlightProperty` and rely on the native trim system. But with SAS override enabled, that won't work at all; instead, we'll want to *not* set the native trim. I guess I'll see if I can implement an option for #40 first, and then discard either the native or internal trim as appropriate. But it looks like the numerical effects may be different in the two paths.

Do we have any idea of how the relevant native systems might change in 1.0? Will we be able to simplify all of this code at some point?
