### ISSUE TITLE
SAS *can't* correct joystick movements

### ISSUE THREAD

**Issue by conklech** [AlexanderDzhoganov/ksp-advanced-flybywire#40]
This is the anti-issue of #28.

As of 1.5.1, we completely override SAS when there's joystick input. In the context of #28, this makes sense. But there are situations where it's unhelpful. For instance, FAR has some flight aids that are designed to be used in conjunction with (i.e. to limit or override) manual input, which are completely disabled by our SAS override. Worse, once controller input touches zero the SAS systems instantly come into full effect, which can be catastrophic in atmospheric flight.

Would it make sense to make the SAS override toggleable?

**Comment by AlexanderDzhoganov** [comment]
+1. Feel free to implement this and make a PR.

**Comment by conklech** [comment]
As mentioned in #39, another problem with the current (9b12c8d73dfc4d2ad9bddb30396ff30310099d2e) system is that native keyboard input and trim settings are ignored when there is AFBW input or AFBW trim in effect.
